title: Your Site Title
description: Your site description
url: "https://viggoforsberg.com" # Replace with your site's URL
author: Your Name

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

# SEO-related options
twitter:
  username: your-twitter-handle
social:
  name: Your Name
  links:
    - https://twitter.com/your-twitter-handle
    - https://www.linkedin.com/in/your-linkedin-profile
    - https://github.com/your-github-profile